- name: setup backend server
  hosts: backend
  become: yes

  tasks:
    - name: disable default nodejs module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs server
      ansible.builtin.package:
        name: nodejs
        state: present
    
    - name: create expense system user
      ansible.builtin.user:
        name: expense

    # Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: delete backend application
      ansible.builtin.file:
        path: /tmp/backend.zip
        state: absent

    - name: download backend application
      ansible.builtin.get_url:
        url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: extract backend application
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy backend service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: daemon reload start and enable
      ansible.builtin.systemd_service:
        name: backend
        enabled: true
        state: started
        daemon_reload: true